repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # ---------------------------------------------------------
  # RUFF (lint + format) 🔥 FONTE ÚNICA
  # ---------------------------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # ---------------------------------------------------------
  # MYPY
  # ---------------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
