from typing import Protocol


class CampaignRepositoryPort(Protocol):
    async def get_events(self, campaign_id: str) -> list: ...
    async def save_events(self, campaign_id: str, events: list): ...
    async def create(self, campaign_id: str) -> None: ...
    async def list(self) -> list[str]: ...
    async def delete(self, campaign_id: str) -> None: ...
    async def exists(self, campaign_id: str) -> bool: ...
