from typing import Protocol, Any


class KeyValueStorePort(Protocol):
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def clear(self) -> None: ...


class VectorStorePort(Protocol):

    def add(self, doc_id: str, vector: list[float]) -> None: ...

    def get(self, doc_id: str) -> list[float] | None: ...

    def search(self, query_vector: list[float], k: int) -> list[str]: ...

    def clear(self) -> None: ...
